sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  - secure: owTAnjqq1Wg3vgOJhepm6cP2sKaNKXCdUMCfubUrLBz8rKg8cNP9WRmu8BBtS3IlY0EnRiNRs72imJjxXxTTYxP0SMTEV9Yr+pOUiIcd1NHt7B2J/N7vvmxlAiHe7bLbGRrC80qIHU1zjmdlQRTy7iQ9V/xZC9U7HGGEzmZqfaBSzE83YByGkyaUSegmcqcHYV8fSuQdNrQptpAUp10xnUUaDF9HUURyH8IlboeTNuLIQVH6U+N0mp6864RlYWwmFVyeLjMvEktF040Jeud8Juqvjm5X9PIWvHsDwFXlATG6EDADtIGkPBsKdS7YggYSk6Z0/0A4jp+XmisL5FPKOvg4ZZ1Q1/EQkFSAfxiCawRrLVbZ9QS6VfYJNE8LU0T+BzhDFr2T9UhEtAJbb5nlFuU/nm2rl21mOFTIiVNsh1mBX4vkDANdjkCfunRkFi4my6GOA9U9suBPuf5sNbaBmeFYurlPntesYGLBOwg/WHFfXQ7ra8S4OE+gf7pYwB8shHcAFfEQOOX92xXpZ7mjtjyv71Nxsv0y4Qv57t9cmltZmQJ9azokrdWZKwNp1ii9IiLLWfwRUHgd25gSZM67lWAPcRPLMSesyv05L6sfTz6rOGL3eg0yIbqO3Kz80Y1lzfUJJWc6L4VfSTWOgdUDrBnDMo8mjs0d8YP7sRq34r8=
after_success:
- python addsettings.py
- mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml
cache:
  directories:
  - "$HOME/.m2"
